rvm:
  - 1.9.3
  - 2.0.0
  
env:
  - RAILS=v4.1.0.beta1 AREL=master
  - RAILS=4-0-stable   AREL=v4.0.1
  - RAILS=3-2-stable   AREL=3-0-stable
  - RAILS=3-1-stable   AREL=2-2-stable
  - RAILS=3-0-stable   AREL=2-0-stable
